# Generated by Django 4.2.1 on 2023-05-24 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_rename_question_text_question_question_txt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_txt',
            new_name='question_text',
        ),
    ]
